### ISSUE TITLE
pango 3.5.0 crashes when require

### ISSUE THREAD

**Issue by scivola** [ruby-gnome/ruby-gnome#1459] opened 2022-01-17 06:19 UTC
pango 3.5.0 crashes when we `require` it.

Reproduction:

```
ruby -r pango -e "p Pango"
```

Log:
[pango.log](https://github.com/ruby-gnome/ruby-gnome/files/7879412/pango.log)

Ruby:

```
ruby 3.1.0p0 (2021-12-25 revision fb4df44d16) [arm64-darwin20]
ruby 3.0.3p157 (2021-11-24 revision 3fb7d2cadc) [arm64-darwin20]
```

Note:

* pango 3.4.9 does not crash
* Does not crash on `ruby 2.7.5p203 (2021-11-24 revision f69aeb8314) [arm64-darwin20]`

**Comment by kou** [comment] 2022-01-17 07:09
This is duplicate of #1456.
Could you try 3.5.1?

**Closed by kou** 2022-01-17 07:09 UTC

**Comment by scivola** [comment] 2022-01-17 08:51
Thank you very much.
It was solved.
