### ISSUE TITLE
gio2: test_string: TypeError: String isn't supported

### ISSUE THREAD

**Issue by mtasaka** [ruby-gnome/ruby-gnome#1296] opened 2019-09-08 14:16 UTC
On Fedora 31, with ruby-gnome master ( 764b86995943c09b2f0f7b62a1f9772fb627256f ) gio2 test fails like:

```
--------------------------------------------------------------------------------
2019-09-08T23:00:32+09:00: Running test for /home/tasaka1/rpmbuild/TEMP/ruby-gnome2/git/ruby-gnome2/gio2
--------------------------------------------------------------------------------
cd resource
glib-compile-resources ruby-gio2.gresource.xml
cd -
cd schema/default
glib-compile-schemas .
cd -
cd schema/source
glib-compile-schemas .
cd -
Loaded suite test
Started
..............E
===============================================================================
Error: test_pathname(TestFile::.open:::path): TypeError: String isn't supported
/home/tasaka1/rpmbuild/TEMP/ruby-gnome2/git/ruby-gnome2/gobject-introspection/lib/gobject-introspection/loader.rb:639:in `invoke'
/home/tasaka1/rpmbuild/TEMP/ruby-gnome2/git/ruby-gnome2/gobject-introspection/lib/gobject-introspection/loader.rb:639:in `invoke'
/home/tasaka1/rpmbuild/TEMP/ruby-gnome2/git/ruby-gnome2/gobject-introspection/lib/gobject-introspection/loader.rb:553:in `block in define_method'
/home/tasaka1/rpmbuild/TEMP/ruby-gnome2/git/ruby-gnome2/gio2/lib/gio2/input-stream.rb:71:in `read_all_raw_compatible'
/home/tasaka1/rpmbuild/TEMP/ruby-gnome2/git/ruby-gnome2/gio2/lib/gio2/input-stream.rb:39:in `block in read'
/home/tasaka1/rpmbuild/TEMP/ruby-gnome2/git/ruby-gnome2/gio2/lib/gio2/input-stream.rb:38:in `loop'
/home/tasaka1/rpmbuild/TEMP/ruby-gnome2/git/ruby-gnome2/gio2/lib/gio2/input-stream.rb:38:in `read'
/home/tasaka1/rpmbuild/TEMP/ruby-gnome2/git/ruby-gnome2/gio2/test/test-file.rb:36:in `block (2 levels) in test_pathname'
     33:         path = Pathname(__FILE__)
     34:         Gio::File.open(path: path) do |file|
     35:           file.read do |input|
  => 36:             assert_equal(File.read(__FILE__), input.read)
     37:           end
     38:         end
     39:       end
/home/tasaka1/rpmbuild/TEMP/ruby-gnome2/git/ruby-gnome2/gio2/lib/gio2/file.rb:56:in `read'
/home/tasaka1/rpmbuild/TEMP/ruby-gnome2/git/ruby-gnome2/gio2/test/test-file.rb:35:in `block in test_pathname'
/home/tasaka1/rpmbuild/TEMP/ruby-gnome2/git/ruby-gnome2/gio2/lib/gio2/file.rb:43:in `open'
/home/tasaka1/rpmbuild/TEMP/ruby-gnome2/git/ruby-gnome2/gio2/test/test-file.rb:34:in `test_pathname'
===============================================================================
E
===============================================================================
Error: test_string(TestFile::.open:::path): TypeError: String isn't supported
/home/tasaka1/rpmbuild/TEMP/ruby-gnome2/git/ruby-gnome2/gobject-introspection/lib/gobject-introspection/loader.rb:639:in `invoke'
/home/tasaka1/rpmbuild/TEMP/ruby-gnome2/git/ruby-gnome2/gobject-introspection/lib/gobject-introspection/loader.rb:639:in `invoke'
/home/tasaka1/rpmbuild/TEMP/ruby-gnome2/git/ruby-gnome2/gobject-introspection/lib/gobject-introspection/loader.rb:553:in `block in define_method'
/home/tasaka1/rpmbuild/TEMP/ruby-gnome2/git/ruby-gnome2/gio2/lib/gio2/input-stream.rb:71:in `read_all_raw_compatible'
/home/tasaka1/rpmbuild/TEMP/ruby-gnome2/git/ruby-gnome2/gio2/lib/gio2/input-stream.rb:39:in `block in read'
/home/tasaka1/rpmbuild/TEMP/ruby-gnome2/git/ruby-gnome2/gio2/lib/gio2/input-stream.rb:38:in `loop'
/home/tasaka1/rpmbuild/TEMP/ruby-gnome2/git/ruby-gnome2/gio2/lib/gio2/input-stream.rb:38:in `read'
/home/tasaka1/rpmbuild/TEMP/ruby-gnome2/git/ruby-gnome2/gio2/test/test-file.rb:27:in `block (2 levels) in test_string'
     24:         path = __FILE__
     25:         Gio::File.open(path: path) do |file|
     26:           file.read do |input|
  => 27:             assert_equal(File.read(__FILE__), input.read)
     28:           end
     29:         end
     30:       end
/home/tasaka1/rpmbuild/TEMP/ruby-gnome2/git/ruby-gnome2/gio2/lib/gio2/file.rb:56:in `read'
/home/tasaka1/rpmbuild/TEMP/ruby-gnome2/git/ruby-gnome2/gio2/test/test-file.rb:26:in `block in test_string'
/home/tasaka1/rpmbuild/TEMP/ruby-gnome2/git/ruby-gnome2/gio2/lib/gio2/file.rb:43:in `open'
/home/tasaka1/rpmbuild/TEMP/ruby-gnome2/git/ruby-gnome2/gio2/test/test-file.rb:25:in `test_string'
===============================================================================
```

... with following similar likes. But gio2 test passes on Fedora 30 - so this must be due to some external library change (probably: Fedora 30 uses GLib 2.60.7 where Fedora 31 uses 2.61.3 , and with GLib 2.62.0 ruby-gnome gio2 test still fails)

**Comment by kou** [comment] 2019-09-08 21:16
Thanks.
This is caused by https://gitlab.gnome.org/GNOME/glib/merge_requests/738 . We need to support this annotation.

**Comment by kou** [comment] 2019-09-09 20:37
It take some times to fix this. This is difficult.
So we'll release a new version for #1294.

**Comment by utkarsh2102** [comment] 2019-10-05 16:06
Hi @kou,
Do we have a fix for this yet?

**Closed** 2019-10-08 21:26 UTC

**Comment by kou** [comment] 2019-10-09 00:34
Fixed.
