### ISSUE TITLE
OutOfMemory error when pango uses cairo

### ISSUE THREAD

**Issue by mark** [ruby-gnome/ruby-gnome#477] opened 2015-07-06 19:51 UTC
I'm on OS X 10.10.4, and getting an OutOfMemory error when using pango.  The error is reported as being in cairo, but only happens when using pango.

The following code errors:

``` ruby
require 'cairo'
require 'pango'

cxt = Cairo::Context.new(Cairo::ImageSurface.new(100, 100))
cxt.save
layout = cxt.create_pango_layout
layout.text = 'Hello, world!'
cxt.show_pango_layout(layout)
cxt.restore
cxt.target.write_to_png('hello_pango.png')
```

On the line `cxt.restore`.  The error as reported is: `test_pango.rb:9:in 'restore': out of memory (NoMemoryError)`

**Comment by andymeneely** [comment] 2015-07-06 20:27
A little bit of context - a bunch of people have run into this problem from my project. Here's the bug report with some more info: https://github.com/andymeneely/squib/issues/88

Weirdly, it works on my Mac and I'm running OSX 10.10.2. I'm using the same versions of Cairo and Pango as they are too.

**Comment by kou** [comment] 2015-07-17 07:34
Sorry. We can't debug on it without debugger.
We can't use debugger unless the problem is ocuured on local machine.

**Comment by kou** [comment] 2022-12-08 06:16
I hope that this was fixed in the latest cairo and macOS.

**Closed by kou** 2022-12-08 06:16 UTC
